schema_version: 1

context:
  version: "2.4.0"

package:
  name: fork-cleaner
  version: ${{ version }}

source:
  url: https://github.com/caarlos0/fork-cleaner/archive/v${{ version }}.tar.gz
  sha256: 28ded4826d8a36d25857b824bea1ae480c76029ff50e8d831f79e18c360ff032

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - fork-cleaner --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Cleans up old and inactive forks on your GitHub account
  homepage: https://github.com/caarlos0/fork-cleaner
  repository: https://github.com/caarlos0/fork-cleaner

extra:
  recipe-maintainers:
    - danielnachun
